---
apiVersion: v1
kind: Service
metadata:
  name: caddy-mesh-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: caddy-mesh
    component: controller
spec:
  selector:
    app: caddy-mesh
    component: controller
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  internalTrafficPolicy: Local
