---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-mesh-proxy-configmap
  namespace: {{ .Release.Namespace }}
data:
  Caddyfile: |
    {
      debug
      admin 0.0.0.0:2019
    }

    :80 {
      log

      respond /healthz 200
    }
