---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caddy-mesh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: caddy-mesh
    component: proxy
automountServiceAccountToken: false
