---
apiVersion: v1
kind: Service
metadata:
  name: caddy-mesh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: caddy-mesh
    component: proxy
spec:
  selector:
    app: caddy-mesh
    component: proxy
  ports:
  - name: web
    protocol: TCP
    port: 80
  - name: admin
    protocol: TCP
    port: 2019
  internalTrafficPolicy: Local
